# CONSTANTS for DECISION TREE
DEFAULT_LEVELS_CONST = 4
VALUE_TO_PREVENT_NaN_CONST = 1 #0.9999999999999999
LEVEL_OF_START_CONST = 0
NUMBER_OF_DIFFERENT_LEVEL_TREES_CONST = 0.5 # this constant indicates the proportion of amount of attributes which will be treated. The rest of them will be dismissed.

DEFAULT_NUMBER_NEIGHBOURS_CONST = 7
MAX_DISCRETE_CONST = -99999999999999999
MIN_DISCRETE_CONST = 99999999999999999
CROSS_VALIDATION_PARTITIONS_CONST = 10
PERCENTAGE_CONST = 100
LEVEL_BY_NUMBER_CONST = 2
DEFAULT_TREATMENT_CONST = "none"
DT_CONST = "DecisionTree"
NN_CONST = "NearestNeighbours"
CONTINUOUS_CONST = "continuous"
NOMINAL_CONST = "nominal"
BINARY_CONST = "binary"
MINKOWSKI_DISTANCE_CONST = 3
